/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.javakt.views;

import com.mycompany.javakt.models.NhanVien;
import com.mycompany.javakt.models.PhongBan;
import com.mycompany.javakt.renderers.PhongBanComponentRenderer;
import com.mycompany.javakt.views.interfaces.NhanVienView;
import java.awt.event.ActionListener;
import java.util.List;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.MutableComboBoxModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;

/**
 * @author To Trung Tin
 */
public class NHANVIEN extends javax.swing.JFrame implements NhanVienView {

    DefaultTableModel tbm
            = new DefaultTableModel(
                    new String[][]{}, new String[]{"Mã số", "Tên Nhân Viên", "Mức Lương", "Phòng Ban"});

    MutableComboBoxModel<PhongBan> cbm = new DefaultComboBoxModel<PhongBan>();
    private List<PhongBan> pbList;

    private String idSelected;

    public ActionListener onAdd;
    public ActionListener onEdit;
    public ActionListener onDelete;
    public ActionListener onChangeToPhongBan;

    /**
     * Creates new form NHANVIEN
     */
    public NHANVIEN() {
        initComponents();
        tblNhanvien.setModel(tbm);
        cbbPhongban.setModel(cbm);
        cbbPhongban.setRenderer(new PhongBanComponentRenderer());
        this.idSelected = "";
        this.txtTenNV.setText("");
        this.txtMucluong.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JTextField();
        txtMucluong = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanvien = new javax.swing.JTable();
        btnEdit = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cbbPhongban = new javax.swing.JComboBox<>();
        btnNew = new javax.swing.JButton();
        btnPhongBan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tên Nhân Viên");

        jLabel2.setText("Mức Lương :");

        txtTenNV.setText("jTextField1");

        txtMucluong.setText("jTextField1");

        tblNhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblNhanvien.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(tblNhanvien);

        btnEdit.setText("EDIT");

        btnAdd.setText("ADD");

        btnDelete.setText("DELETE");

        jLabel3.setText("Phòng Ban :");

        btnNew.setText("NEW");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnPhongBan.setText("Phòng Ban");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtTenNV, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMucluong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                .addComponent(cbbPhongban, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(btnAdd)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnNew)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnEdit)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnDelete)
                            .addGap(18, 18, 18)
                            .addComponent(btnPhongBan))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMucluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbbPhongban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnAdd)
                    .addComponent(btnNew)
                    .addComponent(btnEdit)
                    .addComponent(btnPhongBan))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        this.idSelected = "";
        this.txtTenNV.setText("");
        this.txtMucluong.setText("");
        this.cbbPhongban.setSelectedIndex(0);
    }//GEN-LAST:event_btnNewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info
                    : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NHANVIEN.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NHANVIEN.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NHANVIEN.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NHANVIEN.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(
                new Runnable() {
            public void run() {
                new NHANVIEN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnPhongBan;
    private javax.swing.JComboBox<PhongBan> cbbPhongban;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNhanvien;
    private javax.swing.JTextField txtMucluong;
    private javax.swing.JTextField txtTenNV;
    // End of variables declaration//GEN-END:variables
  @Override
    public void open() {
        this.setVisible(true);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    @Override
    public void setOnAdd(ActionListener onAdd) {
        this.onAdd = onAdd;
    }

    @Override
    public void setOnEdit(ActionListener onEdit) {
        this.onEdit = onEdit;
    }

    @Override
    public void setOnDelete(ActionListener onDelete) {
        this.onDelete = onDelete;
    }

    @Override
    public void setOnChangePhongBan(ActionListener onChangePhongBan) {
        this.onChangeToPhongBan = onChangePhongBan;
    }

    @Override
    public void NapdulieuchoTable(List<NhanVien> list) {
        for (NhanVien nv : list) {
            tbm.addRow(
                    new String[]{
                        String.valueOf(nv.getMaNV()),
                        nv.getTenNV(),
                        String.valueOf(nv.getMucLuong()),
                        nv.getPhongBan().getTenPB()
                    });
        }
    }

    @Override
    public void XoaBang() {
        tbm.setRowCount(0);
    }

    @Override
    public void addRow(NhanVien nv) {
        tbm.addRow(
                new String[]{
                    String.valueOf(nv.getMaNV()),
                    nv.getTenNV(),
                    String.valueOf(nv.getMucLuong()),
                    nv.getPhongBan().getTenPB()
                });
    }

    @Override
    public String getIdSelected() {
        return this.idSelected;
    }

    @Override
    public void initEvents() {
        btnDelete.addActionListener(onDelete);
        btnEdit.addActionListener(onEdit);
        btnAdd.addActionListener(onAdd);
        btnPhongBan.addActionListener(onChangeToPhongBan);
        tblNhanvien
                .getSelectionModel()
                .addListSelectionListener(
                        (ListSelectionEvent event) -> {
                            if (tblNhanvien.getSelectedRow() >= 0) {
                                this.idSelected
                                = tblNhanvien.getValueAt(tblNhanvien.getSelectedRow(), 0).toString();
                                this.txtTenNV.setText(
                                        tblNhanvien.getValueAt(tblNhanvien.getSelectedRow(), 1).toString());
                                this.txtMucluong.setText(
                                        tblNhanvien.getValueAt(tblNhanvien.getSelectedRow(), 2).toString());
                                setSelectedValue(tblNhanvien.getValueAt(tblNhanvien.getSelectedRow(), 3).toString());
                            }
                        });
    }

    public void setSelectedValue(String value) {
        PhongBan item;
        for (int i = 0; i < this.cbbPhongban.getItemCount(); i++) {
            item = (PhongBan) this.cbbPhongban.getItemAt(i);
            if (item.getTenPB().equalsIgnoreCase(value)) {
                this.cbbPhongban.setSelectedIndex(i);
                break;
            }
        }
    }

    @Override
    public String getTenNV() {
        return this.txtTenNV.getText();
    }

    @Override
    public String getMucLuong() {
        return this.txtMucluong.getText();
    }

    public void initDataCompobox(List<PhongBan> pblist) {
        this.pbList = pblist;
        for (PhongBan pb : pblist) {
            cbm.addElement(pb);
        }
    }

    @Override
    public long getMaPB() {
        PhongBan pb = phongBanSelected();
        return pb.getMaPB();
    }

    public PhongBan phongBanSelected() {
        PhongBan pb = (PhongBan) cbbPhongban.getSelectedItem();
        return pb;
    }

}
